# Generated by Django 2.1.1 on 2018-10-28 23:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a class name', max_length=20)),
                ('coursenumber', models.IntegerField(validators=[django.core.validators.MaxValueValidator(80000), django.core.validators.MinValueValidator(70000)])),
                ('description', models.TextField(max_length=100)),
                ('credits', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comments', models.TextField(max_length=100)),
                ('gened', models.CharField(max_length=3)),
                ('major', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a class name', max_length=20)),
                ('classnumber', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('time', models.TimeField(blank=True, null=True)),
                ('semester', models.CharField(max_length=6)),
                ('location', models.CharField(max_length=25)),
                ('textbook', models.CharField(max_length=25)),
                ('students', models.IntegerField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)])),
                ('available', models.IntegerField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)])),
                ('prerequisites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspire.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=20)),
                ('review', models.TextField(max_length=100)),
                ('taught', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspire.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('idnumber', models.IntegerField(validators=[django.core.validators.MaxValueValidator(40000000), django.core.validators.MinValueValidator(30000000)])),
                ('email', models.EmailField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('pronouns', models.CharField(max_length=25)),
                ('emergency', models.CharField(max_length=25)),
                ('coursestaken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspire.Course')),
            ],
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspire.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='reccomendation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspire.CourseInstance'),
        ),
    ]
