# Generated by Django 2.1.1 on 2018-11-03 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0002_auto_20181101_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='coursestaken',
            new_name='coursetaken',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='totalEnrolled',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='courseinstance',
            name='students',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='students',
            field=models.ManyToManyField(to='inspire.Student'),
        ),
    ]
