# Generated by Django 2.1.1 on 2018-11-03 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0003_auto_20181103_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='totalEnrolled',
        ),
        migrations.RemoveField(
            model_name='courseinstance',
            name='students',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='students',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
