# Generated by Django 2.1.1 on 2018-11-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0004_auto_20181103_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='coursetaken',
            new_name='coursestaken',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='basecourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basecourse', to='inspire.Course'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='studentname',
            field=models.ManyToManyField(to='inspire.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='coursesnow',
            field=models.ManyToManyField(related_name='coursesnow', to='inspire.CourseInstance'),
        ),
        migrations.AddField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='shoppingcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoppingcart', to='inspire.CourseInstance'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='prerequisites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisites', to='inspire.Course'),
        ),
        migrations.AddField(
            model_name='days',
            name='daysofweek',
            field=models.ManyToManyField(related_name='daysofweek', to='inspire.CourseInstance'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='days',
            field=models.ManyToManyField(to='inspire.Days'),
        ),
    ]
