# Generated by Django 2.1.1 on 2018-11-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0005_auto_20181103_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reccomendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspire.Course'),
        ),
    ]
