# Generated by Django 2.1.1 on 2018-11-03 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0006_auto_20181103_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='prerequisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisites', to='inspire.Course'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='taught',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspire.CourseInstance'),
        ),
    ]
