# Generated by Django 2.1.1 on 2018-11-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0007_auto_20181103_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='days',
            field=models.ManyToManyField(blank=True, to='inspire.Days'),
        ),
        migrations.AlterField(
            model_name='days',
            name='daysofweek',
            field=models.ManyToManyField(blank=True, related_name='daysofweek', to='inspire.CourseInstance'),
        ),
    ]
