# Generated by Django 2.1.1 on 2018-11-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0008_auto_20181104_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='shoppingcart',
        ),
        migrations.AddField(
            model_name='student',
            name='shoppingcart',
            field=models.ManyToManyField(related_name='shoppingcart', to='inspire.CourseInstance'),
        ),
    ]
