# Generated by Django 2.1.1 on 2018-11-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0009_auto_20181104_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='coursestaken',
        ),
        migrations.AddField(
            model_name='student',
            name='coursestaken',
            field=models.ManyToManyField(to='inspire.Course'),
        ),
    ]
