# Generated by Django 2.1.1 on 2018-11-04 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0010_auto_20181104_2201'),
        ('inspire', '0009_auto_20181104_2248'),
    ]

    operations = [
    ]
