# Generated by Django 2.1.1 on 2018-11-04 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspire', '0011_merge_20181104_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(max_length=200)),
                ('giver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspire.Student')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='professor',
            name='review',
        ),
        migrations.AlterField(
            model_name='professor',
            name='taught',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspire.CourseInstance'),
        ),
        migrations.AddField(
            model_name='professor',
            name='review',
            field=models.ManyToManyField(to='inspire.Reviews'),
        ),
    ]
